import './globals.css'
import {AiFillGithub, AiFillTwitterCircle} from 'react-icons/ai'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-full">
      <body className="container">
        <nav className="rounded-full bg-white my-2 p-4 flex justify-between">
          <h1>josh mccoy</h1>
          <ul className="flex items-center space-x-10">
            <li>Link #1</li>
            <li>Link #1</li>
            <li>Link #1</li>
          </ul>
        </nav>
        {children}
        <div className="min-w-full fixed bottom-0">
          <footer className="w-96 mx-auto">
            <ul className="flex justify-center text-2xl">
              <li><AiFillGithub /></li>
              <li><AiFillTwitterCircle /></li>
            </ul>
          </footer>
        </div>
      </body>
    </html>
  )
}